# Generated by Django 2.1.7 on 2019-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestation',
            name='name',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
